native: true
plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"]
svgoConfig:
  plugins:
    - name: preset-default
      params:
        overrides:
          removeViewBox: false
    - name: removeDimensions
    - name: prefixIds
