autoInstallPeers: false
catalog:
  "@aa-sdk/core": &aaSDK ^4.86.1
  "@account-kit/infra": *aaSDK
  "@account-kit/smart-contracts": *aaSDK
  eslint: &eslint ^9.39.4
  "@eslint/js": *eslint
  tamagui: &tamagui ^1.144.4
  "@tamagui/animations-moti": *tamagui
  "@tamagui/babel-plugin": *tamagui
  "@tamagui/config": *tamagui
  "@tamagui/lucide-icons": *tamagui
  "@tamagui/toast": *tamagui
  "@wagmi/core": ^3.4.1
  hono: ^4.12.14
  i18next: ^26.0.5
  ioredis: ^5.10.1
  react: &react "19.2.0"
  react-dom: *react
  typescript: ^5.9.3
  valibot: ^1.3.1
  viem: ^2.47.6
  wagmi: ^3.6.0
ignoreWorkspaceRootCheck: true
includeWorkspaceRoot: true
minimumReleaseAge: 1440
packages:
  - "."
  - common
  - contracts
  - docs
  - server
  - substreams
  - .maestro
publicHoistPattern:
  - "@babel/runtime"
  - "@react-native/assets-registry"
  - "@react-native/gradle-plugin"
  - "@sentry/cli"
  - expo-asset
  - expo-modules-autolinking
  - react-native-web
  - sharp
