autoInstallPeers: false
ignoreWorkspaceRootCheck: true
includeWorkspaceRoot: true
packages:
  - "."
  - common
  - contracts
  - docs
  - server
  - .maestro
publicHoistPattern:
  - "@babel/runtime"
  - "@react-native/assets-registry"
  - "@react-native/gradle-plugin"
  - "@sentry/cli"
  - expo-asset
  - expo-modules-autolinking
  - react-native-web
