encryptionsalt: v1::v1:AAAAAAAAAAAAAAAb:rYjVO7/uF2+Qv1LhWq5c2S0ZR4rZaQ==
config:
  gcp:project: eexxxaa
  exa:domain: web.exactly.app
  exa:alchemyActivityId: wh_4ogmb0nyymhatwru # cspell:ignore 4ogmb0nyymhatwru
