name: exactly
region: sfo
domains:
  - domain: web.exactly.app
    type: PRIMARY
envs:
  - key: APP_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
services:
  - name: server
    dockerfile_path: Dockerfile
    github:
      repo: exactly/mobile
      branch: main
      deploy_on_push: true
    http_port: 3000
    envs:
      - key: POSTGRES_URL
        scope: RUN_TIME
        value: ${postgres.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
databases:
  - cluster_name: redis
    name: postgres
    production: true
    engine: PG
    version: "16"
  - cluster_name: redis
    name: redis
    production: true
    engine: REDIS
    version: "7"
ingress:
  rules:
    - component:
        name: server
      match:
        path:
          prefix: /
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
