name: ${ENVIRONMENT}
region: sfo
domains:
  - domain: ${APP_DOMAIN}
    type: PRIMARY
envs:
  - key: APP_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
services:
  - name: server
    image:
      registry_type: GHCR
      registry: exactly
      repository: exa-${ENVIRONMENT}
      registry_credentials: ${GHCR_CREDENTIALS}
      digest: ${IMAGE_DIGEST_SERVER}
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb # cspell:ignore vcpu
    log_destinations:
      - name: opensearch
        open_search:
          cluster_name: ${OPENSEARCH_NAME}
          index_name: logs
          basic_auth:
            user: doadmin # cspell:ignore doadmin
    envs:
      - key: POSTGRES_URL
        scope: RUN_TIME
        value: ${postgres.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: ALCHEMY_ACTIVITY_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALCHEMY_ACTIVITY_ID
        scope: RUN_TIME
      - key: ALCHEMY_BLOCK_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALCHEMY_WEBHOOKS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CRYPTOMATE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CRYPTOMATE_URL
        scope: RUN_TIME
      - key: CRYPTOMATE_WEBHOOK_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KEEPER_PRIVATE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ONESIGNAL_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PERSONA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PERSONA_TEMPLATE_ID
        scope: RUN_TIME
      - key: PERSONA_URL
        scope: RUN_TIME
      - key: PERSONA_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SEGMENT_WRITE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SENTRY_DSN
        scope: RUN_TIME
      - key: PANDA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PANDA_API_URL
        scope: RUN_TIME
      - key: PANDA_ISSUING
        scope: RUN_TIME
workers:
  - name: substreams
    source_dir: /substreams/
    image:
      registry_type: GHCR
      registry: exactly
      repository: substreams-${ENVIRONMENT}
      registry_credentials: ${GHCR_CREDENTIALS}
      digest: ${IMAGE_DIGEST_SUBSTREAMS}
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb # cspell:ignore vcpu
    envs:
      - key: POSTGRES_URL
        scope: RUN_TIME
        value: ${postgres.DATABASE_URL}
      - key: SUBSTREAMS_API_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: SUBSTREAMS_ENDPOINTS_CONFIG_${NETWORK}
        scope: RUN_TIME
databases:
  - name: postgres
    cluster_name: ${POSTGRES_NAME}
    production: true
    engine: PG
    version: "16"
    db_name: defaultdb # cspell:ignore defaultdb
    db_user: doadmin # cspell:ignore doadmin
  - name: redis
    cluster_name: ${REDIS_NAME}
    production: true
    engine: REDIS
    version: "7"
  - name: opensearch
    cluster_name: ${OPENSEARCH_NAME}
    production: true
    engine: OPENSEARCH
    version: "2"
ingress:
  rules:
    - component:
        name: server
      match:
        path:
          prefix: /
features:
  - buildpack-stack=ubuntu-22
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
