name: exactly
region: sfo
domains:
  - domain: web.exactly.app
    type: PRIMARY
envs:
  - key: APP_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
  - key: CHAIN_ID
    scope: BUILD_TIME
    value: "10"
services:
  - name: server
    dockerfile_path: Dockerfile
    github:
      repo: exactly/mobile
      branch: main
      deploy_on_push: true
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-d-1vcpu-1gb
    log_destinations:
      - name: opensearch
        open_search:
          cluster_name: exactly-opensearch
          index_name: logs
          basic_auth:
            user: doadmin
    envs:
      - key: POSTGRES_URL
        scope: RUN_TIME
        value: ${postgres.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: ALCHEMY_ACTIVITY_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALCHEMY_ACTIVITY_ID
        scope: RUN_TIME
      - key: ALCHEMY_BLOCK_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALCHEMY_WEBHOOKS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANDROID_CERT_FINGERPRINT
        scope: RUN_TIME
      - key: AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: COLLECTOR_ADDRESS
        scope: RUN_TIME
      - key: CRYPTOMATE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CRYPTOMATE_URL
        scope: RUN_TIME
      - key: CRYPTOMATE_WEBHOOK_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KEEPER_PRIVATE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ONESIGNAL_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PERSONA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PERSONA_TEMPLATE_ID
        scope: RUN_TIME
      - key: PERSONA_URL
        scope: RUN_TIME
      - key: SEGMENT_WRITE_KEY
        scope: RUN_TIME
databases:
  - name: postgres
    cluster_name: exactly-postgres
    production: true
    engine: PG
    version: "16"
    db_name: defaultdb
    db_user: doadmin
  - name: redis
    cluster_name: exactly-redis
    production: true
    engine: REDIS
    version: "7"
  - name: opensearch
    cluster_name: exactly-opensearch
    production: true
    engine: OPENSEARCH
    version: "2"
ingress:
  rules:
    - component:
        name: server
      match:
        path:
          prefix: /
features:
  - buildpack-stack=ubuntu-22
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
