appId: ${APP_ID ?? "app.exactly"}
tags: [critical]
---
- launchApp: { clearState: true, permissions: { all: deny, camera: allow } }
- runFlow: ../subflows/hideDevtools.yaml
- tapOn: Sign in
- assertNotVisible: Sign in
- runFlow: ../subflows/dismissNotifications.yaml
- runScript: ../dist/getAccount.js
- assertVisible: ${output.account.slice(0, 6)}…${output.account.slice(-4)}
- runFlow:
    file: ../subflows/mint.yaml
    env: { asset: USDC, to: "${output.account}", amount: "420" }
- runFlow:
    file: ../subflows/send.yaml
    env: { asset: USDC, to: "${output.owner}", amount: "69" }
- runFlow:
    file: ../subflows/borrow.yaml
    env: { amount: "10", installments: "4" }
- runFlow: ../subflows/rollover.yaml
- runFlow: ../subflows/repay.yaml
- runFlow: ../subflows/verifyIdentity.yaml
- runFlow: ../subflows/activateCard.yaml
- runFlow: ../subflows/storeCoverage.yaml
