appId: app.exactly
tags:
  - critical
---
- launchApp: { clearState: true, permissions: { all: deny, camera: allow } }
- runFlow: ../subflows/hideDevtools.yaml
- runFlow: ../subflows/signIn.yaml
- assertVisible: Stay updated
- tapOn: Not now
- pressKey: home
- launchApp: { permissions: { all: deny, camera: allow } }
- extendedWaitUntil: { visible: Your portfolio, timeout: 180000 }
- assertNotVisible: Stay updated
- runFlow: ../subflows/readPortfolio.yaml
- evalScript: ${output.portfolioBefore = output.portfolio}
- runScript: ../dist/getAccount.js
- runScript:
    file: ../dist/mint.js
    env: { asset: USDC, to: "${output.account}", amount: "420" }
- swipe: { direction: DOWN }
- runFlow: ../subflows/readPortfolio.yaml
- assertTrue: ${output.portfolio - output.portfolioBefore === 420}
- evalScript: ${output.portfolioBefore = output.portfolio}
- runScript: ../dist/getAccount.js
- runFlow:
    file: ../subflows/sendAsset.yaml
    env: { asset: USDC, to: "${output.owner}", amount: "69" }
- runFlow: ../subflows/readPortfolio.yaml
- assertTrue: ${output.portfolioBefore - output.portfolio === 69}
- runFlow:
    when: { visible: Getting Started }
    commands:
      - tapOn: View all steps
      - runFlow: ../subflows/verifyIdentity.yaml
- swipe: { direction: DOWN }
- assertNotVisible: Getting Started
- runFlow: ../subflows/storeCoverage.yaml
