appId: ${APP_ID ?? "app.exactly"}
tags:
  - critical
---
- launchApp: { clearState: true, permissions: { all: deny, camera: allow } }
- runFlow: ../subflows/hideDevtools.yaml
- runScript: ../dist/getAccount.js
- tapOn: Sign in
- runFlow:
    when: { true: "${maestro.platform != 'web'}" }
    commands:
      - assertVisible: Stay updated
      - tapOn: Not now
      - pressKey: home
      - launchApp: { permissions: { all: deny, camera: allow } }
      - extendedWaitUntil: { visible: Your portfolio, timeout: 180000 }
      - assertNotVisible: Stay updated
- assertVisible: ${output.account.slice(0, 6)}…${output.account.slice(-4)}
- runFlow: ../subflows/readPortfolio.yaml
- evalScript: ${output.portfolioBefore = output.portfolio}
- runScript: ../dist/getAccount.js
- runScript:
    file: ../dist/mint.js
    env: { asset: USDC, to: "${output.account}", amount: "420" }
- runFlow:
    when: { true: "${maestro.platform != 'web'}" }
    commands:
      - swipe: { direction: DOWN }
- runFlow: # HACK
    when: { platform: web }
    commands: [{ tapOn: Activity }, { tapOn: Card }, { tapOn: Home }]
- runFlow: ../subflows/readPortfolio.yaml
- assertTrue: ${output.portfolio - output.portfolioBefore === 420}
- evalScript: ${output.portfolioBefore = output.portfolio}
- runScript: ../dist/getAccount.js
- runFlow:
    file: ../subflows/sendAsset.yaml
    env: { asset: USDC, to: "${output.owner}", amount: "69" }
- runFlow: ../subflows/readPortfolio.yaml
- assertTrue: ${output.portfolioBefore - output.portfolio === 69}
- runFlow:
    when: { visible: Getting Started }
    commands:
      - tapOn: View all steps
      - tapOn: Begin verifying
      - runFlow: ../subflows/verifyIdentity.yaml
      - swipe: { direction: DOWN }
      - assertNotVisible: Getting Started
- runFlow: ../subflows/storeCoverage.yaml
