appId: ${APP_ID ?? "app.exactly"}
tags: [production]
---
- launchApp: { clearState: true, permissions: { all: deny, camera: allow } }
- runFlow: ../subflows/hideDevtools.yaml
- runFlow: ../subflows/signIn.yaml
- runFlow: { when: { visible: Stay updated }, commands: [{ tapOn: Not now }] }
- runFlow: ../subflows/readPortfolio.yaml
- assertTrue: ${output.portfolio > 1}
