CREATE TABLE IF NOT EXISTS accounts (
  id BIGSERIAL PRIMARY KEY,
  address BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS deposits (
  id TEXT PRIMARY KEY,
  receiver BYTEA NOT NULL,
  market BYTEA NOT NULL,
  amount TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS swaps (
  id TEXT PRIMARY KEY,
  receiver BYTEA NOT NULL,
  from_asset_id BYTEA NOT NULL,
  to_asset_id BYTEA NOT NULL,
  from_amount TEXT NOT NULL,
  to_amount TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transfers (
  id BIGSERIAL PRIMARY KEY,
  asset BYTEA NOT NULL,
  receiver BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS transfers_all (
  id BIGSERIAL PRIMARY KEY,
  asset BYTEA NOT NULL,
  receiver BYTEA NOT NULL
);