name: e2e:local
on: { push: { branches: ["main"] }, pull_request: {}, workflow_dispatch: {} }
defaults: { tools: { node: "24.13.0", pnpm: "10.28.1" } }
jobs:
  android_get:
    type: get-build
    params:
      platform: android
      profile: e2e:local
      fingerprint_hash: 18bc7d298adcd44cf32edf472e14185322fd61b2
      wait_for_in_progress: true

  android_e2e:
    needs: [android_get]
    environment: development
    runs_on: linux-large-nested-virtualization
    image: latest
    env: { CHAIN_ID: "31337" }
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - uses: eas/install_maestro
      - name: exa setup
        run: | # cspell:ignore tlsv1.2
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --default-toolchain none -y && . $HOME/.cargo/env
          mkdir -p $HOME/workingdir/bin && cd $HOME/workingdir/bin
          for repo in firehose-ethereum substreams substreams-sink-sql; do
            curl -L "$(curl -s https://api.github.com/repos/streamingfast/$repo/releases/latest | jq --arg arch "$(uname -m | sed 's/aarch64/arm64/')" -r '.assets[] | select(.browser_download_url | test("linux_" + $arch)) | .browser_download_url')" | tar zxf -
          done
          cd $HOME/workingdir/build
          pnpm nx e2e server > server.log 2>&1 &
          for i in {1..120}; do
            curl -f http://localhost:3000/api/auth/authentication > /dev/null 2>&1 && break
            [ $i -eq 120 ] && cat server.log && exit 1
            sleep 1
          done
      - uses: eas/download_build
        id: download
        with: { build_id: "${{ needs.android_get.outputs.build_id }}" }
      - name: start emulator # cspell:ignore avdmanager getprop logcat netfast setsid swiftshader noop
        run: |
          adb kill-server && adb start-server

          # put avd writable images on tmpfs to eliminate nested-virt i/o penalty
          AVD_DIR=/dev/shm/avd
          mkdir -p "$AVD_DIR"
          export ANDROID_AVD_HOME="$AVD_DIR"

          avdmanager -s create avd -n e2e -k "system-images;android-34;google_apis;x86_64" --force
          printf '%s\n' "hw.ramSize=8192" "vm.heapSize=1024" "hw.camera.front=emulated" "hw.camera.back=emulated" >> "$AVD_DIR/e2e.avd/config.ini"

          # diagnostics — verify tmpfs usage
          echo "--- tmpfs diagnostics ---"
          df -h /dev/shm
          ls -la "$AVD_DIR/e2e.avd/"
          echo "--- end diagnostics ---"

          setsid $ANDROID_HOME/emulator/emulator -avd e2e -no-snapshot -no-snapshot-save -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -netfast -no-metrics -memory 8192 -cores 4 -partition-size 4096 -wipe-data > emulator-process.log 2>&1 &
          adb wait-for-device
          timeout 180 adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          timeout 60 sh -c 'until adb shell pm list packages > /dev/null 2>&1; do sleep 1; done'

          # tune guest kernel for nested virt — reduce per-i/o overhead
          adb root && adb wait-for-device
          adb shell 'cat /sys/block/vd*/queue/scheduler 2>/dev/null; for d in /sys/block/vd*; do echo none > "$d/queue/scheduler" 2>/dev/null; echo 0 > "$d/queue/read_ahead_kb" 2>/dev/null; done' || true
          adb shell 'echo 0 > /proc/sys/vm/swappiness' || true
          adb unroot && adb wait-for-device

          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb install "${{ steps.download.outputs.artifact_path }}"

          # trigger gms module discovery then wait for system to truly settle.
          # the previous 15-pass uiautomator gate passed too quickly — gms was
          # still downloading and the combined load killed the kernel 54s into
          # maestro. use cpu-idle monitoring to ensure gms is actually done.
          adb shell monkey -p app.exactly 1 2>/dev/null || true
          echo "waiting for guest cpu to settle..."
          prev_idle=0; prev_total=0; settled=0
          for i in $(seq 1 180); do
            cpu=$(timeout 5 adb shell cat /proc/stat 2>/dev/null | head -1)
            if [ -n "$cpu" ]; then
              idle=$(echo "$cpu" | awk '{print $5}')
              total=$(echo "$cpu" | awk '{s=0; for(i=2;i<=NF;i++) s+=$i; print s}')
              if [ "$prev_total" -gt 0 ]; then
                di=$((idle - prev_idle)); dt=$((total - prev_total))
                if [ "$dt" -gt 0 ]; then
                  pct=$((100 * di / dt))
                  echo "cpu idle: ${pct}% (attempt $i, settled=$settled)"
                  if [ "$pct" -gt 80 ]; then
                    settled=$((settled + 1))
                    [ "$settled" -ge 10 ] && echo "system settled" && break
                  else
                    settled=0
                  fi
                fi
              fi
              prev_idle=$idle; prev_total=$total
            else
              settled=0; prev_idle=0; prev_total=0
              adb kill-server 2>/dev/null; adb start-server 2>/dev/null; adb wait-for-device 2>/dev/null || true
            fi
            sleep 2
          done
          [ "$settled" -ge 10 ] || { echo "system never settled"; exit 1; }

          adb shell am force-stop app.exactly
          adb devices -l
          adb reverse tcp:3000 tcp:3000 && adb reverse tcp:8545 tcp:8545 && adb reverse tcp:8969 tcp:8969
      - name: run maestro # cspell:ignore bugreport
        run: |
          # emulator health monitor — detect hangs faster than maestro's timeout
          (while true; do
            if ! timeout 10 adb shell getprop ro.build.type >/dev/null 2>&1; then
              echo "EMULATOR UNRESPONSIVE at $(date -u +%H:%M:%S)"
              timeout 30 adb bugreport emulator-bugreport-crash 2>&1 || true
              break
            fi
            sleep 5
          done) &
          MONITOR_PID=$!

          pnpm e2e:maestro -e "EXPO_PUBLIC_E2E_MNEMONIC=${{ env.EXPO_PUBLIC_E2E_MNEMONIC }}"
          MAESTRO_EXIT=$?

          kill $MONITOR_PID 2>/dev/null || true
          exit $MAESTRO_EXIT
      - name: exa teardown
        if: always()
        run: | # cspell:ignore pkill bugreport
          curl -X POST http://localhost:3000/e2e/shutdown || true
          for i in {1..60}; do [ -f server/coverage/lcov.info ] && break; sleep 1; done
          curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
          ./codecov -t ${{ env.CODECOV_TOKEN }} -f server/coverage/lcov.info -f server/coverage/app.json -F e2e -n android --build-url ${{ workflow.url }}
          timeout 60 adb logcat -d -v time > emulator.log 2>&1 || true
          timeout 60 adb bugreport emulator-bugreport || true
      - uses: eas/upload_artifact
        if: always()
        with:
          type: other
          ignore_error: true
          path: |
            server.log
            server/coverage
            server/node_modules/@exactly/.spotlight
            emulator.log
            emulator-process.log
            emulator-bugreport.zip
            emulator-bugreport-crash.zip
            ${{ env.HOME }}/.maestro/tests
            .maestro/screenshots
