name: e2e:local
on: { push: { branches: ["main"] }, pull_request: {}, workflow_dispatch: {} }
defaults: { tools: { node: "24.13.0", pnpm: "10.28.1" } }
jobs:
  android_get:
    type: get-build
    params:
      platform: android
      profile: e2e:local
      fingerprint_hash: 18bc7d298adcd44cf32edf472e14185322fd61b2
      wait_for_in_progress: true

  android_e2e:
    needs: [android_get]
    environment: development
    runs_on: linux-large-nested-virtualization
    image: latest
    env: { CHAIN_ID: "31337" }
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - uses: eas/install_maestro
      - name: exa setup
        run: | # cspell:ignore tlsv1.2
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --default-toolchain none -y && . $HOME/.cargo/env
          mkdir -p $HOME/workingdir/bin && cd $HOME/workingdir/bin
          for repo in firehose-ethereum substreams substreams-sink-sql; do
            curl -L "$(curl -s https://api.github.com/repos/streamingfast/$repo/releases/latest | jq --arg arch "$(uname -m | sed 's/aarch64/arm64/')" -r '.assets[] | select(.browser_download_url | test("linux_" + $arch)) | .browser_download_url')" | tar zxf -
          done
          cd $HOME/workingdir/build
          pnpm nx e2e server > server.log 2>&1 &
          for i in {1..60}; do
            curl -f http://localhost:3000/api/auth/authentication > /dev/null 2>&1 && break
            [ $i -eq 60 ] && cat server.log && exit 1
            sleep 1
          done
      - uses: eas/download_build
        id: download
        with: { build_id: "${{ needs.android_get.outputs.build_id }}" }
      - name: start emulator # cspell:ignore avdmanager getprop logcat netfast setsid swiftshader
        run: |
          adb kill-server && adb start-server

          # put avd writable images on tmpfs to eliminate nested-virt i/o penalty
          AVD_DIR=/dev/shm/avd
          mkdir -p "$AVD_DIR"
          export ANDROID_AVD_HOME="$AVD_DIR"

          avdmanager -s create avd -n e2e -k "system-images;android-34;google_apis;x86_64" --force
          printf '%s\n' "hw.ramSize=8192" "vm.heapSize=1024" "hw.camera.front=emulated" "hw.camera.back=emulated" >> "$AVD_DIR/e2e.avd/config.ini"
          setsid $ANDROID_HOME/emulator/emulator -avd e2e -no-snapshot -no-snapshot-save -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -netfast -no-metrics -memory 8192 -cores 4 -partition-size 4096 -wipe-data > emulator-process.log 2>&1 &
          adb wait-for-device
          timeout 180 adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          timeout 60 sh -c 'until adb shell pm list packages > /dev/null 2>&1; do sleep 1; done'
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb install "${{ steps.download.outputs.artifact_path }}"
          adb shell monkey -p app.exactly 1 2>/dev/null || true
          stable=0; attempts=0
          while [ $stable -lt 15 ]; do
            attempts=$((attempts + 1))
            [ $attempts -gt 150 ] && echo "emulator not stable after 5min" && exit 1
            if timeout 10 adb shell uiautomator dump /dev/null 2>/dev/null; then
              stable=$((stable + 1))
            else
              stable=0
              adb kill-server 2>/dev/null; adb start-server 2>/dev/null; adb wait-for-device 2>/dev/null || true
            fi
            sleep 2
          done
          adb shell am force-stop app.exactly
          adb devices -l
          adb reverse tcp:3000 tcp:3000 && adb reverse tcp:8545 tcp:8545 && adb reverse tcp:8969 tcp:8969
      - name: run maestro # cspell:ignore bugreport
        run: |
          # emulator health monitor — detect hangs faster than maestro's timeout
          (while true; do
            if ! timeout 10 adb shell getprop ro.build.type >/dev/null 2>&1; then
              echo "EMULATOR UNRESPONSIVE at $(date -u +%H:%M:%S)"
              timeout 30 adb bugreport emulator-bugreport-crash 2>&1 || true
              break
            fi
            sleep 5
          done) &
          MONITOR_PID=$!

          pnpm e2e:maestro -e "EXPO_PUBLIC_E2E_MNEMONIC=${{ env.EXPO_PUBLIC_E2E_MNEMONIC }}"
          MAESTRO_EXIT=$?

          kill $MONITOR_PID 2>/dev/null || true
          exit $MAESTRO_EXIT
      - name: exa teardown
        if: always()
        run: | # cspell:ignore pkill bugreport
          curl -X POST http://localhost:3000/e2e/shutdown || true
          for i in {1..60}; do [ -f server/coverage/lcov.info ] && break; sleep 1; done
          curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
          ./codecov -t ${{ env.CODECOV_TOKEN }} -f server/coverage/lcov.info -f server/coverage/app.json -F e2e -n android --build-url ${{ workflow.url }}
          timeout 60 adb logcat -d -v time > emulator.log 2>&1 || true
          timeout 60 adb bugreport emulator-bugreport || true
      - uses: eas/upload_artifact
        if: always()
        with:
          type: other
          ignore_error: true
          path: |
            server.log
            server/coverage
            server/node_modules/@exactly/.spotlight
            emulator.log
            emulator-process.log
            emulator-bugreport.zip
            emulator-bugreport-crash.zip
            ${{ env.HOME }}/.maestro/tests
            .maestro/screenshots
