name: e2e:local
on: { workflow_dispatch: {} }
defaults: { tools: { node: "24.12.0", pnpm: "10.28.0" } }
jobs:
  fingerprint:
    type: fingerprint
    environment: development
    env: { APP_DOMAIN: localhost, CHAIN_ID: "31337" }

  ios_get:
    type: get-build
    needs: [fingerprint]
    params:
      platform: ios
      profile: e2e:local
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      wait_for_in_progress: true

  ios_build:
    type: build
    needs: [ios_get]
    if: ${{ !needs.ios_get.outputs.build_id }}
    params: { platform: ios, profile: e2e:local }

  ios_repack:
    type: repack
    needs: [ios_get]
    if: ${{ needs.ios_get.outputs.build_id }}
    params: { build_id: "${{ needs.ios_get.outputs.build_id }}" }

  ios_e2e:
    after: [ios_repack, ios_build]
    needs: [fingerprint]
    environment: development
    runs_on: macos-large
    image: latest
    env: { CHAIN_ID: "31337" }
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - uses: eas/install_maestro
      - name: exa setup
        run: | # cspell:ignore tlsv1.2
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --default-toolchain none -y && . $HOME/.cargo/env
          mkdir -p $HOME/workingdir/bin && cd $HOME/workingdir/bin
          for repo in firehose-ethereum substreams substreams-sink-sql; do
            curl -L "$(curl -s https://api.github.com/repos/streamingfast/$repo/releases/latest | jq --arg arch "$(uname -m | sed 's/aarch64/arm64/')" -r '.assets[] | select(.browser_download_url | test("darwin_" + $arch)) | .browser_download_url')" | tar zxf -
          done
          cd $HOME/workingdir/build
          pnpm nx e2e server > server.log 2>&1 &
          for i in {1..60}; do
            curl -f http://localhost:3000/api/auth/authentication > /dev/null 2>&1 && break
            [ $i -eq 60 ] && cat server.log && exit 1
            sleep 1
          done
      - uses: eas/download_build
        id: download
        with: { build_id: "${{ needs.ios_build.outputs.build_id || needs.ios_repack.outputs.build_id }}" }
      - name: install metal toolchain
        run: |
          if xcodebuild -showComponent metalToolchain >/dev/null 2>&1; then
            echo "metal toolchain already installed"
          else
            echo "downloading metal toolchain..."
            xcodebuild -downloadComponent metalToolchain
          fi
      - name: attempt gpu/metal workarounds
        run: |
          # check if any gpu is discoverable
          system_profiler SPDisplaysDataType || true

          # try to enable metal hud (might trigger metal initialization)
          launchctl setenv MTL_HUD_ENABLED 1 || true

          # set metal debug layer (might provide fallback behavior)
          launchctl setenv MTL_DEBUG_LAYER 1 || true

          # attempt to set simulator gpu preference
          defaults write com.apple.CoreSimulator GpuResourcePreference -string "prefer-discrete" || true
          defaults write com.apple.iphonesimulator GraphicsOverride -int 0 || true

          # restart simulator services to pick up changes
          killall -9 com.apple.CoreSimulator.CoreSimulatorService 2>/dev/null || true
      - uses: eas/start_ios_simulator
      - name: diagnostics
        run: |
          echo "=== macOS and Xcode ==="
          sw_vers
          xcodebuild -version

          echo "=== Hardware ==="
          system_profiler SPHardwareDataType

          echo "=== Camera ==="
          system_profiler SPCameraDataType || echo "no camera data"

          echo "=== Display/GPU ==="
          system_profiler SPDisplaysDataType || echo "no display data"

          echo "=== Window Server ==="
          /usr/sbin/system_profiler SPDisplaysDataType 2>&1 | head -50
          pgrep -l WindowServer || echo "no WindowServer process"
          echo "DISPLAY=$DISPLAY"

          echo "=== CoreMediaIO Plugins ==="
          ls -la /Library/CoreMediaIO/Plug-Ins/DAL/ 2>/dev/null || echo "no DAL plugins directory"
          ls -la ~/Library/CoreMediaIO/Plug-Ins/DAL/ 2>/dev/null || echo "no user DAL plugins directory"

          echo "=== Simulator Info ==="
          xcrun simctl list devices booted
          xcrun simctl getenv booted SIMULATOR_CAPABILITIES || echo "no SIMULATOR_CAPABILITIES"

          echo "=== Metal Support ==="
          system_profiler SPDisplaysDataType | grep -i metal || echo "no metal info"

          echo "=== Environment ==="
          env | grep -i -E "(display|gpu|metal|render|screen|window|camera|video)" || echo "no relevant env vars"

          echo "=== Simulator Device Info ==="
          xcrun simctl spawn booted launchctl getenv SIMULATOR_DEVICE_NAME || true
          xcrun simctl spawn booted launchctl getenv SIMULATOR_RUNTIME_VERSION || true

          echo "=== AVFoundation Check (host) ==="
          system_profiler -json SPCameraDataType 2>/dev/null | head -100 || echo "no json camera data"
      - run: xcrun simctl install booted "${{ steps.download.outputs.artifact_path }}"
      - run: xcrun simctl privacy booted grant camera app.exactly
      - run: xcrun simctl spawn booted log stream --predicate 'subsystem contains "app.exactly" or process == "Exa"' > simulator.log 2>&1 &
      - run: pnpm e2e:maestro -e "EXPO_PUBLIC_E2E_MNEMONIC=${{ env.EXPO_PUBLIC_E2E_MNEMONIC }}"
      - name: collect simulator logs
        if: always()
        run: |
          pkill -f "log stream" || true
          xcrun simctl diagnose -b --no-archive --output=simulator-diagnose || true
      - name: exa teardown
        if: always()
        run: |
          curl -X POST http://localhost:3000/e2e/shutdown || true
          for i in {1..60}; do [ -f server/coverage/lcov.info ] && break; sleep 1; done
          curl -Os https://uploader.codecov.io/latest/macos/codecov && chmod +x codecov
          ./codecov -t ${{ env.CODECOV_TOKEN }} -f server/coverage/lcov.info -f server/coverage/app.json -F e2e -n ios --build-url ${{ workflow.url }}
      - uses: eas/upload_artifact
        if: always()
        with:
          type: other
          ignore_error: true
          path: |
            server.log
            simulator.log
            simulator-diagnose
            server/coverage
            server/node_modules/@exactly/.spotlight
            ${{ env.HOME }}/.maestro/tests
            .maestro/screenshots
