import { encodePacked, keccak256 } from "viem";

import paxAssociateIdSecret from "./paxAssociateIdSecret";

/**
 * Derives a deterministic 7-character associate ID from a user's account address.
 * The ID is generated by hashing the account address and the pax associate id secret, then converting to base36.
 *
 * @param account The user's account address.
 * @returns The 7-character associate ID.
 */
export default function deriveAssociateId(account: string): string {
  const hash = keccak256(encodePacked(["address", "string"], [account as `0x${string}`, paxAssociateIdSecret]));
  return BigInt(hash).toString(36).slice(0, 7).toLowerCase();
}
