name: release
on:
  push:
    branches: [main]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ">=9.15.5"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.13.1"
          cache: pnpm
      - uses: foundry-rs/foundry-toolchain@v1
      - run: pnpm install --frozen-lockfile
      - uses: changesets/action@v1
        with:
          title: 🔖 new release
          publish: pnpm changeset publish
          version: ./.changeset/version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
