name: server/production
on:
  push: { tags: ["@exactly/server@*"] }
jobs:
  build:
    uses: ./.github/workflows/server-build.yaml
    with: { stack: production, chain: 10, domain: web.exactly.app }
  deploy:
    needs: build
    uses: ./.github/workflows/server-deploy.yaml
    secrets: inherit
    with: { stack: production, domain: web.exactly.app }
