name: server/base
on:
  push: { branches: [base] }
jobs:
  build:
    uses: ./.github/workflows/server-build.yaml
    with: { stack: base, chain: 8453 }
  deploy:
    needs: build
    uses: ./.github/workflows/server-deploy.yaml
    secrets: inherit
    with: { stack: base }
