name: server/production
on:
  push:
    tags: ["@exactly/server@*"]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  deploy:
    uses: ./.github/workflows/server-deploy.yaml
    secrets: inherit
    with:
      environment: production
      url: https://web.exactly.app
