name: server/sandbox
on:
  push: { branches: [sandbox] }
jobs:
  build:
    uses: ./.github/workflows/server-build.yaml
    with: { stack: sandbox, chain: 11155420, devtools: true }
  deploy:
    needs: build
    uses: ./.github/workflows/server-deploy.yaml
    secrets: inherit
    with: { stack: sandbox }
