name: server/sandbox
on:
  push: { branches: [refund] }
jobs:
  build:
    uses: ./.github/workflows/server-build.yaml
    with: { stack: sandbox, chain: 11155420, devtools: true }
  deploy:
    needs: build
    uses: ./.github/workflows/server-deploy.yaml
    with: { stack: sandbox }
    secrets: { DIGITALOCEAN_TOKEN: "${{ secrets.DIGITALOCEAN_TOKEN }}" }
