name: server/base-sepolia
on:
  push: { branches: [infra] }
jobs:
  build:
    uses: ./.github/workflows/server-build.yaml
    with: { stack: base-sepolia, chain: 84532, devtools: true }
  deploy:
    needs: build
    uses: ./.github/workflows/server-deploy.yaml
    secrets:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    with: { stack: base-sepolia }
